format = '$all'

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[username]
format = '[$user]($style) at '

[hostname]
format = '[$hostname]($style) in '

[c]
disabled = true

[container]
style = 'bold yellow'
format = '[$name]($style) '
