# 字体
# kitty +list-fonts --psnames
font_family      FiraCode Nerd Font Mono
# bold_font        auto
# italic_font      auto
# bold_italic_font auto
font_size 11.0
# 关闭强制从左到右（阿拉伯文从右到左）
force_ltr no
# 任何情况下关闭连字显示
disable_ligatures always

# 鼠标
url_style straight
url_color #0087bd
open_url_with default

# 标签栏
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style angled
